name: Build WPF + InnoSetup

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3

      - name: Instalar Inno Setup
        run: choco install innosetup --yes
        shell: powershell

      - name: Restaurar pacotes NuGet
        run: nuget restore CentralSuporte.sln

      - name: Build do projeto
        run: msbuild CentralSuporte.sln /p:Configuration=Release

      - name: Gerar instalador com Inno Setup
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "instalador\setup.iss"
        shell: powershell

      - name: Upload do instalador como artefato
        uses: actions/upload-artifact@v4
        with:
          name: Instalador
          path: instalador\Output\CentralSuporteSetup.exe
